config/routes.rb
Rails.application.routes.draw do
  resources :process_instances do
    collection do
      get :search
    end
    member do
      resources :process_variables, only: [:update, :update_binary, :data, :delete], param: :name do
        member do
          get :data
          put :update_binary
          delete :delete
        end
      end
      get :diagram
      get :diagram_box
    end
  end

  namespace :history do
    resources :process_instances do
      collection do
        get :search
      end
      member do
        resources :process_variables, only: [:data], param: :name do
          member do
            get :data
          end
        end
      end
    end
  end

  resources :process_jobs, only: [:index, :update, :destroy] do
    member do
      get :stacktrace
      get :stacktrace_box
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin'   => 'sessions#new'
  get '/signout'  => 'sessions#destroy', via: 'delete'

  root 'process_instances#index'
end

app/models/process_instance.rb
class ProcessInstance < ActivitiAbstractModel
  get :all,  '/runtime/process-instances'
  get :find, '/runtime/process-instances/:id'
  delete :destroy, '/runtime/process-instances/:id'
end

app/controllers/history/process_instances_controller.rb
class History::ProcessInstancesController < ApplicationController
  before_filter :check_authenticate
  include ActivitiRawRequestsHelper

  def show
    @instances = HistoryProcessInstance.all('processInstanceId' => params[:id], 'includeProcessVariables' => true).data.to_a
    if @instances.first
      @process_instance = @instances.first
      @variables        = @process_instance.variables.to_a
      sub_processes_params = { superProcessInstanceId: @process_instance.id }
      @sub_processes    = HistoryProcessInstance.paginate(:all, sub_processes_params, page: params[:sub_processes_page])
      @super_process_id = @process_instance.superProcessInstanceId
      @start_time       = Time.parse(@process_instance.startTime)
      @end_time         = Time.parse(@process_instance.endTime) if @process_instance.endTime
      @is_history       = true
      render 'process_instances/show'
    else
      @id = params[:id]
      render 'process_instances/not_found', status: 404
    end
  end
end

app/controllers/process_instances_controller.rb
require 'net/http'

class ProcessInstancesController < ApplicationController
  before_filter :check_authenticate
  layout false, only: [:diagram_box, :diagram]
  include ActivitiRawRequestsHelper

  def index
    search_params = {}
    search_params['processInstanceId'] = params[:process_instance_id] unless params[:process_instance_id].to_s.empty?
    search_params['processDefinitionId'] = params[:process_definition_id] unless params[:process_definition_id].to_s.empty?
    search_params['processDefinitionKey'] = params[:process_definition_key] unless params[:process_definition_key].to_s.empty?
    search_params['businessKey'] = params[:business_key] unless params[:business_key].to_s.empty?
    @process_instances = HistoryProcessInstance.paginate(:all, search_params, page: params[:page])
    redirect_to process_instance_path(id:@process_instances.first.id) if @process_instances.total_entries == 1
  end

  def show
    @instances = ProcessInstance.all(id: params[:id], 'includeProcessVariables' => true).data.to_a
    if @instances.first
      @process_instance = @instances.first
      history_instance  = HistoryProcessInstance.all('processInstanceId' => @process_instance.id).data.to_a.first
      @variables        = @process_instance.variables.to_a.sort_by { |h| h[:name].to_s.downcase }
      @jobs             = Job.all('processInstanceId' => @process_instance.id).data.to_a.sort_by { |h| h[:id].to_i }
      @tasks            = Task.all('processInstanceId' => @process_instance.id).data.to_a.sort_by { |h| h[:id].to_i }
      @executions       = Execution.all('processInstanceId' => @process_instance.id).data.to_a.sort_by { |h| h[:id].to_i }
      sub_processes_params = { superProcessInstanceId: @process_instance.id }
      # TODO: make constants or config params for 1 and 10
      sub_processes_params[:start] = (params[:sub_processes_page].to_i - 1) * 10 if params[:sub_processes_page]
      @sub_processes    = HistoryProcessInstance.paginate(:all, sub_processes_params, page: params[:sub_processes_page])
      @super_process_id = history_instance.superProcessInstanceId
      @start_time       = Time.parse(history_instance.startTime)
    else
      redirect_to history_process_instance_path id: params[:id]
    end
  end

  def destroy
    ProcessInstance.destroy(params[:id])
    flash[:success] = "Process instance #{params[:id]} has been removed."
    redirect_to root_path
  end

  def search
    redirect_to process_instance_path id: params[:id]
  end

  def diagram
    url = "#{session[:api_url]}runtime/process-instances/#{params[:id]}/diagram"
    send_data raw_request(url), type: 'image/png' , disposition: 'attachment'
  end

  def diagram_box
  end
end

app/helpers/process_instances_helper.rb
module ProcessInstancesHelper
  def variable_tag(process_instance, variable)
    is_history = !!process_instance.endTime

    if %w(serializable binary).include? variable.type
      return is_history ? history_variable_data_tag(process_instance.id, variable.name) :
          variable_data_tag(process_instance.id, variable.name)
    end
    return variable.value.to_s if is_history
    variable_edit_tag(process_instance.id, variable.name, variable.value)
  end

  def variable_data_tag(proc_inst_id, name)
    content_tag :div do
      concat link_to 'Get binary data', data_process_variable_path(id: proc_inst_id, name: name)
      concat ' | '
      concat link_to 'Upload binary data', '#', class: 'upload_binary_data_link'
      concat variable_data_form(proc_inst_id, name)
    end
  end

  def variable_data_form(proc_inst_id, name)
    form_tag update_binary_process_variable_path(id: proc_inst_id, name: name), method: :put, multipart: true do
      file_field_tag :file,
                     onchange:'javascript:this.form.submit();',
                     style: 'display: none;'
    end
  end

  def history_variable_data_tag(proc_inst_id, name)
    link_to 'Get binary data', data_history_process_variable_path(id: proc_inst_id, name: name)
  end

  def variable_edit_tag(proc_inst_id, name, value = nil)
    link_to value.to_s, '#',
            class: 'editable variable-editable',
            data: { name: 'value',
                    pk: 'variable',
                    url: process_variable_path(id: proc_inst_id, name: name),
                    title: "Enter value for #{name}",
                    value: value.to_s,
                    type: 'text'
                  }
  end

  def process_variable_delete_tag(proc_inst_id, name)
    form_tag delete_process_variable_path(id: proc_inst_id, name: name), method: :delete do
      button_tag(type: 'submit', class: 'btn btn-default btn-xs', data: { confirm: 'Are you sure?' } ) do
        content_tag :span, ' Remove', class: 'glyphicon glyphicon-trash'
      end
    end
  end

  def process_instance_delete_tag(id)
    form_tag process_instance_path(id: id), method: :delete do
      button_tag(type: 'submit', class: 'btn btn-default btn-lg', data: { confirm: 'Are you sure?' } ) do
        content_tag :span, class: 'glyphicon glyphicon-trash' do
          ' Remove'
        end
      end
    end
  end

  def ended_label_xs_tag
    content_tag :span, 'Ended' ,class: 'label label-warning'
  end

  def no_elements(elements_name)
    content_tag :h2, "No #{elements_name} associated with this process instance."
  end

  def elements_count(elements)
    content_tag :span, elements.to_a.count, class: 'badge'
  end

  def custom_badge(text)
    content_tag :span, text, class: 'badge'
  end

  def history_processes_table_tag(process_instances)
    content_tag :table, class: 'table table-striped table-bordered' do
      concat history_processes_header
      process_instances.each do |process_instance|
        concat history_processes_line process_instance
      end
    end
  end

  def history_processes_header
    content_tag :thead do
      concat content_tag :th, 'Id'
      concat content_tag :th, 'Business key'
      concat content_tag :th, 'Process definition Id'
      concat content_tag :th, 'Start time'
      concat content_tag :th, 'End time'
    end
  end

  def history_processes_line(process_instance)
    content_tag :tr do
      concat content_tag :td, history_process_link(process_instance)
      concat content_tag :td, process_instance.businessKey.to_s
      concat content_tag :td, process_instance.processDefinitionId.to_s
      concat content_tag :td, process_instance.startTime.to_s
      concat content_tag :td, process_instance.endTime.to_s
    end
  end

  def history_process_link(process_instance)
    link = link_to process_instance.id, process_instance_path(id: process_instance.id), data: { no_turbolink: true }
    process_instance.endTime ? link.concat(ended_label_xs_tag) : link
  end
end

app/views/process_instances/show/_executions.html.erb
<% if @executions %>
    <div class="panel panel-default">
      <div class="panel-heading cursor-pointer collapsed" data-toggle="collapse"
           data-target="#collapse_executions" data-parent="#accordion">
        <span class="notification-header collapsed"><strong>Process Executions</strong>
          <%= elements_count(@executions) %></span>
      </div>
      <div id="collapse_executions" class="accordion-body collapse">
        <div class="panel-body accordion-inner">
          <% if @executions.any? %>
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Id</th>
                    <td>Parent Id</td>
                    <th>Activity Id</th>
                  </tr>
                </thead>
                <tbody>
                <% @executions.each do |execution| %>
                    <tr>
                      <td><%= execution.id %></td>
                      <td><%= execution.parentId.to_s %></td>
                      <td><%= execution.activityId.to_s %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% else %>
              <%= no_elements 'Executions' %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/process_instances/show/_jobs.html.erb
<% if @jobs %>
    <div class="panel panel-default">
      <div class="panel-heading cursor-pointer collapsed" data-toggle="collapse"
           data-target="#collapse_jobs" data-parent="#accordion">
        <span class="notification-header collapsed"><strong>Process Jobs</strong>
          <%= elements_count(@jobs) %></span>
      </div>
      <div id="collapse_jobs" class="accordion-body collapse">
        <div class="panel-body accordion-inner">
          <% if @jobs.any? %>
              <table class="table table-striped table-bordered">
                <thead>
                <th>Id</th>
                <th>Retries</th>
                <th>Due date</th>
                <th>Exception Message</th>
                <th>Actions</th>
                </thead>
                <tbody>
                <% @jobs.each do |job| %>
                    <tr>
                      <td><%= job.id %></td>
                      <td><%= job.retries.to_s %></td>
                      <td><%= job.dueDate.to_s %></td>
                      <td><%= link_to job.exceptionMessage.to_s, '#', class: 'fancybox', data: { url: stacktrace_process_job_url(id: job.id)} %></td>
                      <td>
                        <%= job_execute_tag(job.id) %>
                        <%= job_delete_tag(job.id) %>
                      </td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% else %>
            <%= no_elements 'Jobs' %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/process_instances/show/_no_diagram.html.erb
<p>Process instance has no graphical diagram.</p>

app/views/process_instances/show/_subprocesses.html.erb
<div class="panel panel-default">
  <div class="panel-heading cursor-pointer collapsed" data-toggle="collapse"
       data-target="#collapse_subprocesses" data-parent="#accordion">
    <span class="notification-header collapsed"><strong>Process Subprocesses</strong>
      <%= custom_badge(@sub_processes.total_entries) %></span>
  </div>
  <div id="collapse_subprocesses" class="accordion-body collapse">
    <div class="panel-body accordion-inner">
      <% if @sub_processes.any? %>
          <%= history_processes_table_tag @sub_processes %>
          <div align="center"><%= will_paginate @sub_processes, param_name: 'sub_processes_page', params: {anchor: 'subprocesses'} ,renderer: BootstrapPagination::Rails %></div>
      <% else %>
          <%= no_elements 'Subprocesses' %>
      <% end %>
    </div>
  </div>
</div>

app/views/process_instances/show/_tasks.html.erb
<% if @tasks %>
    <div class="panel panel-default">
      <div class="panel-heading cursor-pointer collapsed" data-toggle="collapse"
           data-target="#collapse_tasks" data-parent="#accordion">
        <span class="notification-header collapsed"><strong>Process Tasks</strong>
          <%= elements_count(@tasks) %></span>
      </div>
      <div id="collapse_tasks" class="accordion-body collapse">
        <div class="panel-body accordion-inner">
          <% if @tasks.any? %>
              <table class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Id</th>
                    <th>Created</th>
                    <th>Name</th>
                    <th>Task Definition Key</th>
                  </tr>
                </thead>
                <tbody>
                <% @tasks.each do |task| %>
                    <tr>
                      <td><%= task.id %></td>
                      <td><%= Time.parse(task.createTime).strftime '%Y-%m-%d %H:%M'  %></td>
                      <td><%= task.name.to_s %></td>
                      <td><%= task.taskDefinitionKey.to_s %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>
          <% else %>
              <%= no_elements 'Tasks' %>
          <% end %>
        </div>
      </div>
    </div>
<% end %>

app/views/process_instances/show/_top_row.html.erb
<div class="row">
  <div class="col-md-5">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Process info</strong></div>
      <table class="table table-striped">
        <tbody>
        <tr>
          <td>
            <strong>Process Instance ID:</strong>
          </td>
          <td>
            <%= @process_instance.id %>
            <%= ended_label_xs_tag if @is_history %>
          </td>
        </tr>
        <% unless @process_instance.businessKey.to_s.empty? %>
            <tr>
              <td>
                <strong>Busines key:</strong>
              </td>
              <td>
                <%= @process_instance.businessKey %>
              </td>
            </tr>
        <% end %>
        <% if @super_process_id %>
            <tr>
              <td><strong>Parent process:</strong></td>
              <td>
                <%= link_to @super_process_id, process_instance_path(id: @super_process_id), data: { no_turbolink: true } %>
              </td>
            </tr>
        <% end %>
        <tr>
          <td><strong>Process Definition Id:</strong></td>
          <td><%= @process_instance.processDefinitionId %></td>
        </tr>
        <% unless @is_history %>
            <tr>
              <td><strong>Process diagram:</strong></td>
              <td><%= link_to 'Show', '#', class: 'fancybox', data: { url: diagram_box_process_instance_url } %></td>
            </tr>
        <% end %>
        <tr>
          <td><strong>Start Time:</strong></td>
          <td>
            <%= @start_time.localtime %>
          </td>
        </tr>
        <% if @end_time %>
            <tr>
              <td><strong>End Time:</strong></td>
              <td>
                <%= @end_time.localtime %>
              </td>
            </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Process actions</strong></div>
      <div class="panel-body"><%= process_instance_delete_tag(@process_instance.id) unless @is_history %></div>
    </div>
  </div>
</div>

app/views/process_instances/show/_variables.html.erb
<div class="panel panel-default">
  <div class="panel-heading cursor-pointer collapsed" data-toggle="collapse"
       data-target="#collapse_variables" data-parent="#accordion">
    <span class="notification-header collapsed"><strong>Process Variables</strong>
      <%= elements_count(@variables) %></span>
  </div>
  <div id="collapse_variables" class="accordion-body collapse">
    <div class="panel-body accordion-inner">
      <% if @variables.any? %>
          <table class="table table-striped table-bordered">
            <thead>
            <th>Name</th>
            <th>Type</th>
            <th>Value</th>
            <th>Actions</th>
            </thead>
            <tbody class="variables_searchable">
            <tr><td colspan="4">
              <div class="input-group" style="width: 100%"><span class="input-group-addon">Filter</span>
                <input id="variables_filter" type="text" class="form-control" placeholder="Enter search text...">
              </div>
            </td></tr>
            <% @variables.each do |variable| %>
                <tr class="searchable_data">
                  <td><%= variable.name %></td>
                  <td><%= variable.type %></td>
                  <td><%= variable_tag @process_instance, variable %></td>
                  <td><%= process_variable_delete_tag(@process_instance.id, variable.name) unless @process_instance.endTime %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% else %>
          <%= no_elements 'Variables' %>
      <% end %>
    </div>
  </div>
</div>