config/routes.rb
Rails.application.routes.draw do
  resources :process_instances do
    collection do
      get :search
    end
    member do
      resources :process_variables, only: [:update, :update_binary, :data, :delete], param: :name do
        member do
          get :data
          put :update_binary
          delete :delete
        end
      end
      get :diagram
      get :diagram_box
    end
  end

  namespace :history do
    resources :process_instances do
      collection do
        get :search
      end
      member do
        resources :process_variables, only: [:data], param: :name do
          member do
            get :data
          end
        end
      end
    end
  end

  resources :process_jobs, only: [:index, :update, :destroy] do
    member do
      get :stacktrace
      get :stacktrace_box
    end
  end

  resources :sessions, only: [:new, :create, :destroy]
  get '/signin'   => 'sessions#new'
  get '/signout'  => 'sessions#destroy', via: 'delete'

  root 'process_instances#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActivitiRailsAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <!-- Static navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">Activiti Rails Admin</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to  'Process instances', process_instances_path if signed_in? %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= search_box %>
      <%= profile_urls %>
    </ul>
  </nav>

  <div>
    <% flash.each do |key,value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}", data: { dismiss: 'alert' }) %>
    <% end %>
    <%= yield %>
  </div>
</div>
</body>
</html>